// Maps football-data.org English team names → German names stored in DB
export const EN_TO_DE: Record<string, string> = {
  'Algeria': 'Algerien',
  'Argentina': 'Argentinien',
  'Australia': 'Australien',
  'Austria': 'Österreich',
  'Belgium': 'Belgien',
  'Bosnia-Herzegovina': 'Bosnien-Herzegowina',
  'Bosnia and Herzegovina': 'Bosnien-Herzegowina',
  'Bosnia Herzegovina': 'Bosnien-Herzegowina',
  'Brazil': 'Brasilien',
  'Cabo Verde': 'Kap Verde',
  'Canada': 'Kanada',
  'Cape Verde': 'Kap Verde',
  'Cape Verde Islands': 'Kap Verde',
  'Colombia': 'Kolumbien',
  'Congo DR': 'DR Kongo',
  'DR Congo': 'DR Kongo',
  'Croatia': 'Kroatien',
  'Curaçao': 'Curaçao',
  'Czech Republic': 'Tschechien',
  'Czechia': 'Tschechien',
  "Côte d'Ivoire": 'Elfenbeinküste',
  'Ecuador': 'Ecuador',
  'Egypt': 'Ägypten',
  'England': 'England',
  'France': 'Frankreich',
  'Germany': 'Deutschland',
  'Ghana': 'Ghana',
  'Haiti': 'Haiti',
  'Iran': 'Iran',
  'Iraq': 'Irak',
  'Ivory Coast': 'Elfenbeinküste',
  'Japan': 'Japan',
  'Jordan': 'Jordanien',
  'Korea Republic': 'Südkorea',
  'Republic of Korea': 'Südkorea',
  'South Korea': 'Südkorea',
  'Mexico': 'Mexiko',
  'Morocco': 'Marokko',
  'Netherlands': 'Niederlande',
  'New Zealand': 'Neuseeland',
  'Norway': 'Norwegen',
  'Panama': 'Panama',
  'Paraguay': 'Paraguay',
  'Portugal': 'Portugal',
  'Qatar': 'Katar',
  'Saudi Arabia': 'Saudi-Arabien',
  'Scotland': 'Schottland',
  'Senegal': 'Senegal',
  'South Africa': 'Südafrika',
  'Spain': 'Spanien',
  'Sweden': 'Schweden',
  'Switzerland': 'Schweiz',
  'Tunisia': 'Tunesien',
  'Turkey': 'Türkei',
  'Türkiye': 'Türkei',
  'United States': 'USA',
  'Uruguay': 'Uruguay',
  'Uzbekistan': 'Usbekistan',
}

export function toGermanTeam(name: string): string {
  return EN_TO_DE[name] ?? name
}
