name = "wm-tippspiel"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "wm_tippspiel_db"
database_name = "wm-tippspiel-db"
database_id = "a1761565-0dc5-4bef-8647-3c48517cb412"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "REPLACE_WITH_YOUR_KV_NAMESPACE_ID"

[vars]
NEXTAUTH_URL = "http://localhost:3000"
NODE_ENV = "development"
