name = "wm-tippspiel"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "wm-tippspiel-db"
database_id = "9f270af0-845b-4cea-b3ed-4842be7b235f"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "94c3c8aa214e40d78b618f13e0470743"

[vars]
NODE_ENV = "production"
# TURNSTILE_SECRET_KEY is set via Cloudflare Pages dashboard (Secrets)
